drop table _sys_batch_id;
drop table _sys_file;
drop table _sys_load_id;
drop table out_orders;
drop table src_csv_campaign_channels_merge CASCADE;
drop table src_csv_campaigns_merge CASCADE;
drop table src_csv_categories_products_merge CASCADE;
drop table src_csv_customer_merge CASCADE;
drop table src_csv_customers_merge CASCADE;
drop table src_csv_customers_merge_diff;
drop table src_csv_customers_merge_uniq;
drop table src_csv_ledger_merge CASCADE;
drop table src_csv_orders_merge CASCADE;
drop table src_csv_orders_merge_diff;
drop table src_csv_orders_merge_diff;drop view ls_customers;
drop table src_csv_orders_merge_uniq;
drop table stg_csv_customers_merge;
drop table stg_csv_orders_merge;
drop view ls_campaign_channels;
drop view ls_campaigns;
drop view ls_categories_products;
drop view ls_customers;
drop view ls_ledger;
drop view ls_orders;
